// Copyright (c) 1994-2013 Georgia Tech Research Corporation, Atlanta, GA
// This file is part of FalconView(R).

// FalconView(R) is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// FalconView(R) is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.

// You should have received a copy of the GNU Lesser General Public License
// along with FalconView(R).  If not, see <http://www.gnu.org/licenses/>.

// FalconView(R) is a registered trademark of Georgia Tech Research Corporation.

#include "KMLDrawingLibrary.h"
#include "kml/base/uri_parser.h"
#include "kml_tests.h"
#include <string>

/*static*/ kmldom::ElementPtr KMLTestEnvironment::TEST_KML_ROOT;
/*static*/ size_t KMLTestEnvironment::s_viewformat_url_fetch_count = 0;
/*static*/ size_t KMLTestEnvironment::s_httpquery_url_fetch_count = 0;

std::string g_settable_kml;

const char* TEST_KML_NET_URL = "http://www.example.com/test.kml";
const char* TEST_KML_NET_BASE = "http://www.example.com/";
const char* TEST_KML_NET_TARGET = "test.kml";
const char* TEST_STYLES_KML_URL = "http://www.example.com/styles.kml";
const char* TEST_ARBITRARY_DATA_URL = "http://www.example.com/foo";
const char* TEST_ARBITRARY_DATA_BASE = "http://www.example.com/munch/yada";
const char* TEST_ARBITRARY_DATA_TARGET = "../foo";
const char* TEST_VIEWFORMAT_URL
   = "http://www.example.com/viewformat?BBOX=0,0,10,10";
const char* TEST_HTTPQUERY_URL
   = "http://www.example.com/httpquery?yada=foo&client=FalconView";
const char* SETTABLE_KML_URL = "http://www.example.com/SETTABLE_KML_URL";

bool FetchAsTestDataImpl(const std::string& url, std::string* data)
{
   if (!kmldrawing::InTestEnvironment)
      return false; // don't do this unless we are testing

   if (url == SETTABLE_KML_URL)
   {
      *data = g_settable_kml;
      return true;
   }

   if (url == TEST_VIEWFORMAT_URL)
   {
      ++KMLTestEnvironment::s_viewformat_url_fetch_count;
      return true;
   }

   if (url == TEST_HTTPQUERY_URL)
   {
      ++KMLTestEnvironment::s_httpquery_url_fetch_count;
      return true;
   }

   // remove any fragment or query
   // this is very specific to our tests and is not generalized

   kmlbase::UriParser* parser
      = kmlbase::UriParser::CreateFromParse(url.c_str());
   std::string host, path, scheme;
   parser->GetHost(&host);
   parser->GetPath(&path);
   parser->GetScheme(&scheme);

   std::string parsed(url);
   if (scheme == "http")
   {
      parsed = "http://";
      parsed += host;
      parsed += "/";
      parsed += path;
   }

   // DANGER! Could cause heap corruption if MSVCRT versions differ
   delete parser;

   if (parsed == TEST_KML_NET_URL)
   {
      *data = TEST_KML;
      return true;
   }

   if (parsed == TEST_STYLES_KML_URL)
   {
      *data = STYLES_KML;
      return true;
   }

   if (parsed == TEST_ARBITRARY_DATA_URL)
   {
      *data = ARBITRARY_DATA;
      return true;
   }

   // it wasn't a test "URL," so look in the test data "files"

   std::string as_file_name;
   kmlbase::UriParser::UriToFilename(parsed, &as_file_name);

   auto it = kmldrawing::TestDataMap.find(as_file_name);
   if (it != kmldrawing::TestDataMap.end())
   {
      *data = it->second;
      return true;
   }

   return false;
}

std::string TEST_KML(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <Document>"
   "    <Placemark id=\"simple placemark\">"
   "      <name>Simple placemark</name>"
   "      <description>Attached to the ground</description>"
   "      <styleUrl>styles.kml#iconstyle</styleUrl>"
   "      <Point>"
   "        <coordinates>-122.0822035425683,37.42228990140251,0</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <Placemark id=\"another placemark\">"
   "      <name>Another placemark</name>"
   "      <description>Attached to the ground</description>"
   "      <styleUrl>styles.kml#iconstyle</styleUrl>"
   "      <Point>"
   "        <coordinates>-122.0,37.4,0</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <NetworkLink id=\"netlink\">"
   "      <name>NE US Radar</name>"
   "      <refreshVisibility>1</refreshVisibility>"
   "      <Link>"
   "        <href>http://example.com/brokenlink.kml</href>"
   "      </Link>"
   "    </NetworkLink>"
   "  </Document>"
   "</kml>"
   );

std::string STYLES_KML(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<!--"
   "All style elements with non-default values."
   ""
   "Note: XHTML in CDATA must conform to the HTML Compatibility guidelines as"
   "detailed in http://www.w3.org/TR/xhtml1/#guidelines. See in particular section"
   "C2, which requires <br /> over <br>."
   ""
   "-->"
   "<kml xmlns=\"http://earth.google.com/kml/2.2\">"
   "  <Document>"
   "    <!-- IconStyle -->"
   "    <Style id=\"iconstyle\">"
   "      <IconStyle>"
   "        <scale>1.2</scale>"
   "        <heading>90.5</heading>"
   "        <Icon>"
   "          <href>http://maps.google.com/mapfiles/kml/paddle/4.png</href>"
   "        </Icon>"
   "        <hotSpot x=\"0.1\" y=\"10\" xunits=\"fraction\" yunits=\"pixels\"/>"
   "      </IconStyle>"
   "    </Style>"
   "    <!-- LabelStyle -->"
   "    <Style id=\"labelstyle\">"
   "      <LabelStyle>"
   "        <scale>0.8</scale>"
   "      </LabelStyle>"
   "    </Style>"
   "    <!-- LineStyle -->"
   "    <Style id=\"linestyle\">"
   "      <LineStyle>"
   "        <width>2</width>"
   "      </LineStyle>"
   "    </Style>"
   "    <!-- PolyStyle -->"
   "    <Style id=\"polystyle\">"
   "      <PolyStyle>"
   "        <fill>0</fill>"
   "        <outline>0</outline>"
   "      </PolyStyle>"
   "    </Style>"
   "    <!-- BalloonStyle -->"
   "    <Style id=\"balloonstyle\">"
   "      <BalloonStyle>"
   "        <bgcolor>00112233</bgcolor>"
   "        <textColor>33221100</textColor>"
   "        <text>"
   "        <![CDATA[<b>$[name]</b><br /><br />$[description]]]>"
   "      </text>"
   "      <displayMode>hide</displayMode>"
   "    </BalloonStyle>"
   "  </Style>"
   "  <!-- ListStyle -->"
   "  <Style id=\"liststyle\">"
   "    <ListStyle>"
   "      <listItemType>checkHideChildren</listItemType>"
   "      <bgcolor>00112233</bgcolor>"
   "      <ItemIcon>"
   "        <state>closed</state>"
   "        <href>http://example.com/image.png</href>"
   "      </ItemIcon>"
   "    </ListStyle>"
   "  </Style>"
   "  <!-- StyleMap -->"
   "  <StyleMap id=\"stylemap\">"
   "    <Pair>"
   "      <key>normal</key>"
   "      <styleUrl>http://example.com/style.kml</styleUrl>"
   "    </Pair>"
   "    <Pair>"
   "      <key>highlight</key>"
   "      <Style>"
   "        <!-- yes, inline style is fine -->"
   "        <LabelStyle>"
   "          <scale>0.8</scale>"
   "        </LabelStyle>"
   "      </Style>"
   "    </Pair>"
   "  </StyleMap>"
   "</Document>"
   "</kml>"
   );

std::string ARBITRARY_DATA("They made the sunrise for people like us.");

std::string TEST_COORDINATES_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <Folder>"
   "    <Placemark>"
   "      <Point>"
   "        <coordinates>1,1</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <Placemark>"
   "      <Point>"
   "        <coordinates>0,1,1</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "  </Folder>"
   "</kml>"
   );

std::string TEST_OUTER_BOUNDARY_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <Placemark>"
   "    <Polygon>"
   "      <outerBoundaryIs>"
   "        <LinearRing>"
   "          <coordinates>"
   "            2,2"
   "            0,2"
   "            0,0"
   "            2,0"
   "            2,2"
   "          </coordinates>"
   "        </LinearRing>"
   "      </outerBoundaryIs>"
   "    </Polygon>"
   "  </Placemark>"
   "</kml>"
   );

std::string TEST_LINE_STRING_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <Placemark>"
   "    <LineString>"
   "      <coordinates>"
   "        2,2"
   "        2,0"
   "        0,0"
   "        0,2"
   "      </coordinates>"
   "    </LineString>"
   "  </Placemark>"
   "</kml>"
   );

std::string TEST_MULTI_GEOMETRY_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <Placemark>"
   "    <MultiGeometry>"
   "      <Point>"
   "        <coordinates>0,1</coordinates>"
   "      </Point>"
   "      <LineString>"
   "        <coordinates>"
   "          3,2"
   "          3,0"
   "          1,0"
   "          1,2"
   "        </coordinates>"
   "      </LineString>"
   "      <Polygon>"
   "        <outerBoundaryIs>"
   "          <LinearRing>"
   "            <coordinates>"
   "              6,2"
   "              4,2"
   "              4,0"
   "              6,0"
   "              6,2"
   "            </coordinates>"
   "          </LinearRing>"
   "        </outerBoundaryIs>"
   "      </Polygon>"
   "      <MultiGeometry>"
   "        <Point>"
   "          <coordinates>2,1</coordinates>"
   "        </Point>"
   "      </MultiGeometry>"
   "    </MultiGeometry>"
   "  </Placemark>"
   "</kml>"
   );

std::string TEST_ICON_STYLE_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <Document>"
   "    <Style id=\"test_icon_style\">"
   "      <IconStyle>"
   "        <scale>3.0</scale>"
   "        <heading>90.0</heading>"
   "        <Icon>"
   "          <href>http://osm-kml.appspot.com/static/falconview_symposium.png</href>"
   "        </Icon>"
   "      </IconStyle>"
   "    </Style>"
   "    <Placemark>"
   "      <styleUrl>#test_icon_style</styleUrl>"
   "      <Point>"
   "        <coordinates>1,1</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "  </Document>"
   "</kml>"
   );

std::string TEST_ICON_COLOR_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <Document>"
   "    <Style id=\"green\">"
   "      <IconStyle>"
   "        <color>ff00ff00</color>"
   "      </IconStyle>"
   "    </Style>"
   "    <Style id=\"yellow\">"
   "      <IconStyle>"
   "        <color>ffffff00</color>"
   "      </IconStyle>"
   "    </Style>"
   "    <Style id=\"blue\">"
   "      <IconStyle>"
   "        <color>ff0000ff</color>"
   "      </IconStyle>"
   "    </Style>"
   "    <Style id=\"semitransparent\">"
   "      <IconStyle>"
   "        <color>33333333</color>"
   "      </IconStyle>"
   "    </Style>"
   "    <Placemark>"
   "      <styleUrl>#green</styleUrl>"
   "      <Point>"
   "        <coordinates>0,0</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <Placemark>"
   "      <styleUrl>#yellow</styleUrl>"
   "      <Point>"
   "        <coordinates>0,1</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <Placemark>"
   "      <styleUrl>#blue</styleUrl>"
   "      <Point>"
   "        <coordinates>0,2</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <Placemark>"
   "      <styleUrl>#semitransparent</styleUrl>"
   "      <Point>"
   "        <coordinates>0,3</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <Placemark>"
   "      <styleUrl>#yellow</styleUrl>"
   "      <Point>"
   "        <coordinates>0,4</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <Placemark>"
   "      <styleUrl>#yellow</styleUrl>"
   "      <Point>"
   "        <coordinates>0,5</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <Placemark>"
   "      <styleUrl>#yellow</styleUrl>"
   "      <Point>"
   "        <coordinates>0,6</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <Placemark>"
   "      <styleUrl>#yellow</styleUrl>"
   "      <Point>"
   "        <coordinates>0,7</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <Placemark>"
   "      <styleUrl>#yellow</styleUrl>"
   "      <Point>"
   "        <coordinates>0,8</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <Placemark>"
   "      <Point>"
   "        <coordinates>0,9</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "  </Document>"
   "</kml>"
   );

std::string TEST_POLY_STYLE_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <Document>"
   "    <Style id=\"transparent_red\">"
   "      <PolyStyle>"
   "        <color>880000ff</color>"
   "      </PolyStyle>"
   "    </Style>"
   "    <Placemark>"
   "      <styleUrl>#transparent_red</styleUrl>"
   "      <Polygon>"
   "        <outerBoundaryIs>"
   "          <LinearRing>"
   "            <coordinates>"
   "              2,2"
   "              0,2"
   "              0,0"
   "              2,0"
   "              2,2"
   "            </coordinates>"
   "          </LinearRing>"
   "        </outerBoundaryIs>"
   "      </Polygon>"
   "    </Placemark>"
   "  </Document>"
   "</kml>"
   );

std::string TEST_LINE_STYLE_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <Document>"
   "    <Style id=\"transparent_blue_and_yellow\">"
   "      <PolyStyle>"
   "        <color>88ff0000</color>"
   "      </PolyStyle>"
   "      <LineStyle>"
   "        <color>8800ffff</color>"
   "        <width>6</width>"
   "      </LineStyle>"
   "    </Style>"
   "    <Placemark>"
   "      <styleUrl>#transparent_blue_and_yellow</styleUrl>"
   "      <Polygon>"
   "        <outerBoundaryIs>"
   "          <LinearRing>"
   "            <coordinates>"
   "              2,2"
   "              0,2"
   "              0,0"
   "              2,0"
   "              2,2"
   "            </coordinates>"
   "          </LinearRing>"
   "        </outerBoundaryIs>"
   "      </Polygon>"
   "    </Placemark>"
   "    <Placemark>"
   "      <styleUrl>#transparent_blue_and_yellow</styleUrl>"
   "      <LineString>"
   "        <coordinates>"
   "          5,2"
   "          5,0"
   "          3,0"
   "          3,2"
   "        </coordinates>"
   "      </LineString>"
   "    </Placemark>"
   "  </Document>"
   "</kml>"
   );


std::string TEST_GROUND_OVERLAY_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <Folder>"
   "    <GroundOverlay>"
   "      <Icon>"
   "        <href>http://tile.openstreetmap.org/4/7/7.png</href>"
   "      </Icon>"
   "      <LatLonBox>"
   "        <north>21.943045533438177</north>"
   "        <south>0.0</south>"
   "        <east>0.0</east>"
   "        <west>-22.5</west>"
   "      </LatLonBox>"
   "    </GroundOverlay>"
   "    <GroundOverlay>"
   "      <Icon>"
   "        <href>http://tile.openstreetmap.org/4/8/7.png</href>"
   "      </Icon>"
   "      <LatLonBox>"
   "        <north>21.943045533438177</north>"
   "        <south>0.0</south>"
   "        <east>22.5</east>"
   "        <west>0.0</west>"
   "      </LatLonBox>"
   "    </GroundOverlay>"
   "  </Folder>"
   "</kml>"
   );

std::string TEST_SUPER_OVERLAY_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <Document>"
   "    <GroundOverlay>"
   "      <Region>"
   "        <LatLonAltBox>"
   "          <north>85.0511287798</north>"
   "          <south>-85.0511287798</south>"
   "          <east>180.0</east>"
   "          <west>-180.0</west>"
   "        </LatLonAltBox>"
   "        <Lod>"
   "          <minLodPixels>400</minLodPixels>"
   "          <maxLodPixels>-1</maxLodPixels>"
   "        </Lod>"
   "      </Region>"
   "      <Icon>"
   "        <href>http://tile.openstreetmap.org/0/0/0.png</href>"
   "      </Icon>"
   "      <LatLonBox>"
   "        <north>85.0511287798</north>"
   "        <south>-85.0511287798</south>"
   "        <east>180.0</east>"
   "        <west>-180.0</west>"
   "      </LatLonBox>"
   "    </GroundOverlay>"
   "    <NetworkLink>"
   "      <Region>"
   "        <Lod>"
   "          <minLodPixels>400</minLodPixels>"
   "          <maxLodPixels>-1</maxLodPixels>"
   "        </Lod>"
   "        <LatLonAltBox>"
   "          <north>85.0511287798</north>"
   "          <south>0.0</south>"
   "          <east>0.0</east>"
   "          <west>-180.0</west>"
   "        </LatLonAltBox>"
   "      </Region>"
   "      <Link>"
   "        <href>http://osm-kml.appspot.com/kml?zoom=1&amp;x=0&amp;y=0</href>"
   "        <viewRefreshMode>onRegion</viewRefreshMode>"
   "      </Link>"
   "    </NetworkLink>"
   "    <NetworkLink>"
   "      <Region>"
   "        <Lod>"
   "          <minLodPixels>400</minLodPixels>"
   "          <maxLodPixels>-1</maxLodPixels>"
   "        </Lod>"
   "        <LatLonAltBox>"
   "          <north>85.0511287798</north>"
   "          <south>0.0</south>"
   "          <east>180.0</east>"
   "          <west>0.0</west>"
   "        </LatLonAltBox>"
   "      </Region>"
   "      <Link>"
   "        <href>http://osm-kml.appspot.com/kml?zoom=1&amp;x=1&amp;y=0</href>"
   "        <viewRefreshMode>onRegion</viewRefreshMode>"
   "      </Link>"
   "    </NetworkLink>"
   "    <NetworkLink>"
   "      <Region>"
   "        <Lod>"
   "          <minLodPixels>400</minLodPixels>"
   "          <maxLodPixels>-1</maxLodPixels>"
   "        </Lod>"
   "        <LatLonAltBox>"
   "          <north>0.0</north>"
   "          <south>-85.0511287798</south>"
   "          <east>0.0</east>"
   "          <west>-180.0</west>"
   "        </LatLonAltBox>"
   "      </Region>"
   "      <Link>"
   "        <href>http://osm-kml.appspot.com/kml?zoom=1&amp;x=0&amp;y=1</href>"
   "        <viewRefreshMode>onRegion</viewRefreshMode>"
   "      </Link>"
   "    </NetworkLink>"
   "    <NetworkLink>"
   "      <Region>"
   "        <Lod>"
   "          <minLodPixels>400</minLodPixels>"
   "          <maxLodPixels>-1</maxLodPixels>"
   "        </Lod>"
   "        <LatLonAltBox>"
   "          <north>0.0</north>"
   "          <south>-85.0511287798</south>"
   "          <east>180.0</east>"
   "          <west>0.0</west>"
   "        </LatLonAltBox>"
   "      </Region>"
   "      <Link>"
   "        <href>http://osm-kml.appspot.com/kml?zoom=1&amp;x=1&amp;y=1</href>"
   "        <viewRefreshMode>onRegion</viewRefreshMode>"
   "      </Link>"
   "    </NetworkLink>"
   "  </Document>"
   "</kml>"
   );

std::string TEST_NETWORK_LINK_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <NetworkLink>"
   "    <Link>"
   "      <href>file:///D:/exclude/temp/coordinates.kml</href>"
   "    </Link>"
   "  </NetworkLink>"
   "</kml>"
   );

std::string TEST_RELATIVE_LOAD_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <NetworkLink>"
   "    <Link>"
   "      <href>http://osm-kml.appspot.com/static/network_link_relative.kml</href>"
   "    </Link>"
   "  </NetworkLink>"
   "</kml>"
   );

std::string TEST_NETWORK_SHARED_STYLES_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <NetworkLink>"
   "    <Link>"
   "      <href>http://osm-kml.appspot.com/static/main_not_doc.kmz</href>"
   "    </Link>"
   "  </NetworkLink>"
   "</kml>"
   );

std::string TEST_KMZ_WITHOUT_EXTENSION_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <NetworkLink>"
   "    <Link>"
   "      <href>http://osm-kml.appspot.com/kmz.foo</href>"
   "    </Link>"
   "  </NetworkLink>"
   "</kml>"
   );

std::string TEST_SCREEN_OVERLAY_OVERLAY_XY_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <Folder>"
   "    <ScreenOverlay>"
   "      <overlayXY x=\"407\" y=\"295\" />"
   "      <Icon>"
   "        <href>http://osm-kml.appspot.com/static/falconview_symposium.png</href>"
   "      </Icon>"
   "    </ScreenOverlay>"
   "    <ScreenOverlay>"
   "      <Icon>"
   "        <href>http://osm-kml.appspot.com/static/falconview_symposium.png</href>"
   "      </Icon>"
   "    </ScreenOverlay>"
   "    <ScreenOverlay>"
   "      <overlayXY x=\"0.01\" y=\"295\" xunits=\"fraction\" yunits=\"insetPixels\" />"
   "      <Icon>"
   "        <href>http://osm-kml.appspot.com/static/falconview_symposium.png</href>"
   "      </Icon>"
   "    </ScreenOverlay>"
   "  </Folder>"
   "</kml>"
   );

std::string TEST_SCREEN_OVERLAY_SCREEN_XY_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <Folder>"
   "    <ScreenOverlay>"
   "      <overlayXY x=\"0.0\" y=\"1.0\" xunits=\"fraction\" yunits=\"fraction\" />"
   "      <screenXY x=\"0\" y=\"0\" xunits=\"pixels\" yunits=\"insetPixels\" />"
   "      <Icon>"
   "        <href>http://osm-kml.appspot.com/static/falconview_symposium.png</href>"
   "      </Icon>"
   "    </ScreenOverlay>"
   "    <ScreenOverlay>"
   "      <overlayXY x=\"407\" y=\"295\" />"
   "      <screenXY x=\"0\" y=\"0\" xunits=\"insetPixels\" yunits=\"insetPixels\" />"
   "      <Icon>"
   "        <href>http://osm-kml.appspot.com/static/falconview_symposium.png</href>"
   "      </Icon>"
   "    </ScreenOverlay>"
   "    <ScreenOverlay>"
   "      <overlayXY x=\"1.0\" y=\"0.0\" xunits=\"fraction\" yunits=\"fraction\" />"
   "      <screenXY x=\"1.0\" y=\"0.0\" xunits=\"fraction\" yunits=\"fraction\" />"
   "      <Icon>"
   "        <href>http://osm-kml.appspot.com/static/falconview_symposium.png</href>"
   "      </Icon>"
   "    </ScreenOverlay>"
   "    <ScreenOverlay>"
   "      <overlayXY x=\"0\" y=\"0\" />"
   "      <screenXY x=\"0\" y=\"0\" xunits=\"pixels\" yunits=\"pixels\" />"
   "      <Icon>"
   "        <href>http://osm-kml.appspot.com/static/falconview_symposium.png</href>"
   "      </Icon>"
   "    </ScreenOverlay>"
   "    <ScreenOverlay>"
   "      <screenXY x=\"0.5\" y=\"0.5\" xunits=\"fraction\" yunits=\"fraction\" />"
   "      <Icon>"
   "        <href>http://osm-kml.appspot.com/static/falconview_symposium.png</href>"
   "      </Icon>"
   "    </ScreenOverlay>"
   "  </Folder>"
   "</kml>"
   );

std::string TEST_SCREEN_OVERLAY_ROTATION_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <Folder>"
   "    <ScreenOverlay>"
   "      <Icon>"
   "        <href>http://osm-kml.appspot.com/static/falconview_symposium.png</href>"
   "      </Icon>"
   "      <overlayXY x=\"0.0\" y=\"1.0\" xunits=\"fraction\" yunits=\"fraction\" />"
   "      <screenXY x=\"0.0\" y=\"1.0\" xunits=\"fraction\" yunits=\"fraction\" />"
   "      <rotation>-45.0</rotation>"
   "    </ScreenOverlay>"
   "  </Folder>"
   "</kml>"
   );

std::string TEST_SCREEN_OVERLAY_SIZE_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <Folder>"
   "    <ScreenOverlay>"
   "      <Icon>"
   "        <href>http://osm-kml.appspot.com/static/falconview_symposium.png</href>"
   "      </Icon>"
   "      <overlayXY x=\"0.0\" y=\"1.0\" xunits=\"fraction\" yunits=\"fraction\" />"
   "      <screenXY x=\"0.0\" y=\"1.0\" xunits=\"fraction\" yunits=\"fraction\" />"
   "      <size x=\"100\" y=\"0\" xunits=\"pixels\" yunits=\"pixels\" />"
   "    </ScreenOverlay>"
   "    <ScreenOverlay>"
   "      <Icon>"
   "        <href>http://osm-kml.appspot.com/static/falconview_symposium.png</href>"
   "      </Icon>"
   "      <size x=\"0\" y=\"0.5\" xunits=\"fraction\" yunits=\"fraction\" />"
   "      <rotation>-45.0</rotation>"
   "    </ScreenOverlay>"
   "    <ScreenOverlay>"
   "      <Icon>"
   "        <href>http://osm-kml.appspot.com/static/falconview_symposium.png</href>"
   "      </Icon>"
   "      <overlayXY x=\"1.0\" y=\"0.0\" xunits=\"fraction\" yunits=\"fraction\" />"
   "      <screenXY x=\"1.0\" y=\"0.0\" xunits=\"fraction\" yunits=\"fraction\" />"
   "      <size x=\"-1\" y=\"30\" xunits=\"pixels\" yunits=\"pixels\" />"
   "    </ScreenOverlay>"
   "    <ScreenOverlay>"
   "      <overlayXY x=\"1.0\" y=\"1.0\" xunits=\"fraction\" yunits=\"fraction\" />"
   "      <screenXY x=\"1.0\" y=\"1.0\" xunits=\"fraction\" yunits=\"fraction\" />"
   "      <Icon>"
   "        <href>http://osm-kml.appspot.com/static/falconview_symposium.png</href>"
   "      </Icon>"
   "      <size x=\"300\" y=\"50\" />"
   "    </ScreenOverlay>"
   "  </Folder>"
   "</kml>"
   );

std::string TEST_NETWORK_LINK_WINFORMAT_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <NetworkLink>"
   "    <Link>"
   "      <href>D:\\exclude\\temp\\coordinates.kml</href>"
   "    </Link>"
   "  </NetworkLink>"
   "</kml>"
   );

std::string TEST_NETWORK_LINK_LOCAL_RELATIVE_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <NetworkLink>"
   "    <Link>"
   "      <href>coordinates.kml</href>"
   "    </Link>"
   "  </NetworkLink>"
   "</kml>"
   );

std::string TEST_KML_REDIRECT_KML_DATA(
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <NetworkLink>"
   "    <Link>"
   "      <href>http://osm-kml.appspot.com/kml-redirect</href>"
   "    </Link>"
   "  </NetworkLink>"
   "</kml>"
   );

std::string TEST_RELATIVE_KMZ_NESTED_KML_DATA(
   "<kml>"
   "  <NetworkLink>"
   "    <Link>"
   "      <href>http://osm-kml.appspot.com/static/relative_kmzs.kml</href>"
   "    </Link>"
   "  </NetworkLink>"
   "</kml>"
   );

std::string TEST_STYLE_MAP_KML_DATA(
   "<kml>"
   "  <Placemark>"
   "    <StyleMap>"
   "      <Pair>"
   "        <key>highlight</key>"
   "        <Style>"
   "          <IconStyle>"
   "            <scale>0.7</scale>"
   "            <heading>250.941903659358</heading>"
   "            <Icon>"
   "              <href>http://www.falconview.org/trac/FalconView/chrome/site/FalconLogo.png</href>"
   "            </Icon>"
   "          </IconStyle>"
   "          <LineStyle>"
   "            <color>5cffdf36</color>"
   "            <width>3</width>"
   "          </LineStyle>"
   "        </Style>"
   "      </Pair>"
   "      <Pair>"
   "        <key>normal</key>"
   "        <Style>"
   "          <IconStyle>"
   "            <scale>0.5</scale>"
   "            <heading>250.941903659358</heading>"
   "            <Icon>"
   "              <href>http://www.falconview.org/trac/FalconView/chrome/site/FalconLogo.png</href>"
   "            </Icon>"
   "          </IconStyle>"
   "          <LabelStyle>"
   "            <scale>0</scale>"
   "          </LabelStyle>"
   "          <LineStyle>"
   "            <color>5cffdf36</color>"
   "            <width>0</width>"
   "          </LineStyle>"
   "        </Style>"
   "      </Pair>"
   "    </StyleMap>"
   "    <MultiGeometry>"
   "      <Point>"
   "        <altitudeMode>absolute</altitudeMode>"
   "        <coordinates>"
   "          1,1,11582"
   "        </coordinates>"
   "      </Point>"
   "    </MultiGeometry>"
   "  </Placemark>"
   "</kml>"
   );

std::string TEST_BALLOON_STYLE_KML_DATA(
   "<kml xmlns=\"http://www.opengis.net/kml/2.2\">"
   "  <Document>"
   "    <Style id=\"exampleBalloonStyle\">"
   "      <BalloonStyle>"
   "        <bgColor>ffffffbb</bgColor>"
   "        <text>"
   "          <![CDATA["
   "          <b><font color=\"#CC0000\" size=\"+3\">$[name]</font></b>"
   "          ($[id])"
   "          <br/><br/>"
   "          <font face=\"Courier\">$[description]</font>"
   "          <br/><br/>"
   "          Extra text that will appear in the description balloon"
   "          <br/><br/>"
   "          $[Snippet]"
   "          <br/><br/>"
   "          $[not_supported_by_ge_either_but_still_displayed]"
   "          <br/><br/>"
   "          $[address]"
   "          <br/><br/>"
   "          $[geDirections]"
   "          ]]>"
   "        </text>"
   "      </BalloonStyle>"
   "    </Style>"
   "    <Placemark id=\"sample placemark\">"
   "      <name>BalloonStyle</name>"
   "      <address>250 14th Street NW, Atlanta, GA, 30318</address>"
   "      <description>An example of BalloonStyle</description>"
   "      <Snippet maxLines=\"3\">"
   "        We were born without time."
   "        Nameless in the eyes"
   "        Of a mother, a father and God."
   "        When the world would wait for us"
   "        A thousand years in the crush"
   "        Of our eyes, fearless, in awe."
   "      </Snippet>"
   "      <styleUrl>#exampleBalloonStyle</styleUrl>"
   "      <Point>"
   "        <coordinates>2,2,0</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "  </Document>"
   "</kml>"
   );

std::string TEST_VIEWFORMAT_KML(
   "<kml>"
   "  <NetworkLink>"
   "    <Link>"
   "      <href>http://www.example.com/viewformat</href>"
   "      <viewFormat>BBOX=[bboxWest],[bboxSouth],[bboxEast],[bboxNorth]</viewFormat>"
   "    </Link>"
   "  </NetworkLink>"
   "</kml>"
   );

std::string TEST_HTTPQUERY1_KML_DATA(
   "<kml>"
   "  <NetworkLink>"
   "    <Link>"
   "      <href>http://www.example.com/httpquery</href>"
   "      <httpQuery>yada=foo&amp;client=FalconView</httpQuery>"
   "    </Link>"
   "  </NetworkLink>"
   "</kml>"
   );

std::string TEST_HTTPQUERY2_KML_DATA(
   "<kml>"
   "  <NetworkLink>"
   "    <Link>"
   "      <href>"
   "        http://www.example.com/httpquery?"
   "      </href>"
   "      <httpQuery>"
   "        <![CDATA[yada=foo&client=FalconView]]>"
   "      </httpQuery>"
   "    </Link>"
   "  </NetworkLink>"
   "</kml>"
   );

std::string TEST_HTTPQUERY3_KML_DATA(
   "<kml>"
   "  <NetworkLink>"
   "    <Link>"
   "      <href>http://www.example.com/httpquery?yada=foo&amp;</href>"
   "      <httpQuery>client=[clientName]</httpQuery>"
   "    </Link>"
   "  </NetworkLink>"
   "</kml>"
   );

std::string TEST_TREE_CONTROL_KML_DATA(
   "<kml>"
   "  <Document>"
   "    <name>Expanded Document With Four Children</name>"
   "    <open>1</open>"
   "    <Document>"
   "      <name>Document With No Children</name>"
   "    </Document>"
   "    <Document>"
   "      <name>Document With No Children and Not Visible</name>"
   "      <visibility>0</visibility>"
   "    </Document>"
   "    <Folder>"
   "      <name>Closed Folder With One Child</name>"
   "      <Document>"
   "        <name>Closed Document With One Child and Not Visible</name>"
   "        <visibility>0</visibility>"
   "        <open>0</open>"
   "        <Document>"
   "          <name>Empty Folder</name>"
   "        </Document>"
   "      </Document>"
   "    </Folder>"
   "    <Folder>"
   "      <name>Jumps to Top Document</name>"
   "    </Folder>"
   "  </Document>"
   "</kml>"
   );

std::string TEST_POLY_FILLS_KML_DATA(
   "<kml>"
   "  <Folder>"
   "    <Placemark>"
   "      <Style>"
   "        <LineStyle>"
   "          <color>88ffff00</color>"
   "          <width>3.5</width>"
   "        </LineStyle>"
   "        <PolyStyle>"
   "          <color>880000ff</color>"
   "          <fill>1</fill>"
   "          <outline>1</outline>"
   "        </PolyStyle>"
   "      </Style>"
   "      <Polygon>"
   "        <outerBoundaryIs>"
   "          <LinearRing>"
   "            <coordinates>1,1 0,1 0,0 1,0 1,1</coordinates>"
   "          </LinearRing>"
   "        </outerBoundaryIs>"
   "      </Polygon>"
   "    </Placemark>"
   "    <Placemark>"
   "      <Style>"
   "        <LineStyle>"
   "          <color>88ffff00</color>"
   "          <width>3.5</width>"
   "        </LineStyle>"
   "        <PolyStyle>"
   "          <color>880000ff</color>"
   "          <fill>0</fill>"
   "          <outline>1</outline>"
   "        </PolyStyle>"
   "      </Style>"
   "      <Polygon>"
   "        <outerBoundaryIs>"
   "          <LinearRing>"
   "            <coordinates>3,1 2,1 2,0 3,0 3,1</coordinates>"
   "          </LinearRing>"
   "        </outerBoundaryIs>"
   "      </Polygon>"
   "    </Placemark>"
   "    <Placemark>"
   "      <Style>"
   "        <LineStyle>"
   "          <color>88ffff00</color>"
   "          <width>3.5</width>"
   "        </LineStyle>"
   "        <PolyStyle>"
   "          <color>880000ff</color>"
   "          <fill>1</fill>"
   "          <outline>0</outline>"
   "        </PolyStyle>"
   "      </Style>"
   "      <Polygon>"
   "        <outerBoundaryIs>"
   "          <LinearRing>"
   "            <coordinates>5,1 4,1 4,0 5,0 5,1</coordinates>"
   "          </LinearRing>"
   "        </outerBoundaryIs>"
   "      </Polygon>"
   "    </Placemark>"
   "    <Placemark>"
   "      <Style>"
   "        <LineStyle>"
   "          <color>88ffff00</color>"
   "          <width>3.5</width>"
   "        </LineStyle>"
   "        <PolyStyle>"
   "          <color>880000ff</color>"
   "          <fill>0</fill>"
   "          <outline>0</outline>"
   "        </PolyStyle>"
   "      </Style>"
   "      <Polygon>"
   "        <outerBoundaryIs>"
   "          <LinearRing>"
   "            <coordinates>7,1 6,1 6,0 7,0 7,1</coordinates>"
   "          </LinearRing>"
   "        </outerBoundaryIs>"
   "      </Polygon>"
   "    </Placemark>"
   "  </Folder>"
   "</kml>"
   );

std::string TEST_LABEL_STYLE_KML_DATA(
   "<kml>"
   "  <Document>"
   "    <Style id=\"randomLabelColor\">"
   "      <LabelStyle>"
   "        <color>ff0000cc</color>"
   "        <colorMode>random</colorMode>"
   "        <scale>1.5</scale>"
   "      </LabelStyle>"
   "    </Style>"
   "    <Placemark>"
   "      <name>LabelStyle.kml</name>"
   "      <styleUrl>#randomLabelColor</styleUrl>"
   "      <Point>"
   "        <coordinates>3.14,2.71,0</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "  </Document>"
   "</kml>");

std::string TEST_REFRESH_ON_INTERVAL_KML_DATA(
   "<kml>"
   "  <!-- GE does this very poorly without the Document tag or with lots of points. -->"
   "  <Document>"
   "    <NetworkLink>"
   "      <Link>"
   "        <href>http://osm-kml.appspot.com/random_kml</href>"
   "        <refreshMode>onInterval</refreshMode>"
   "        <refreshInterval>3.14</refreshInterval>"
   "      </Link>"
   "    </NetworkLink>"
   "  </Document>"
   "</kml>");

std::string TEST_POLY_INNER_RINGS_KML_DATA(
   "<kml>"
   "  <Placemark>"
   "    <Style>"
   "      <LineStyle>"
   "        <color>88ffff00</color>"
   "        <width>3.5</width>"
   "      </LineStyle>"
   "      <PolyStyle>"
   "        <color>880000ff</color>"
   "        <fill>1</fill>"
   "        <outline>1</outline>"
   "      </PolyStyle>"
   "    </Style>"
   "    <Polygon>"
   "      <outerBoundaryIs>"
   "        <LinearRing>"
   "          <coordinates>10,10 0,10 0,0 10,0 10,10</coordinates>"
   "        </LinearRing>"
   "      </outerBoundaryIs>"
   "      <innerBoundaryIs>"
   "        <LinearRing>"
   "          <coordinates>5,5 1,5 1,1 5,1 5,5</coordinates>"
   "        </LinearRing>"
   "      </innerBoundaryIs>"
   "      <innerBoundaryIs>"
   "        <LinearRing>"
   "          <coordinates>3,3 2,3 2,2 3,2 3,3</coordinates>"
   "        </LinearRing>"
   "      </innerBoundaryIs>"
   "      <innerBoundaryIs>"
   "        <LinearRing>"
   "          <coordinates>8,8 6,8 6,6 8,6 8,8</coordinates>"
   "        </LinearRing>"
   "      </innerBoundaryIs>"
   "    </Polygon>"
   "  </Placemark>"
   "</kml>");

std::string TEST_POLY_INNER_RINGS_NOFILL_KML_DATA(
   "<kml>"
   "  <Placemark>"
   "    <Style>"
   "      <LineStyle>"
   "        <color>88ffff00</color>"
   "        <width>3.5</width>"
   "      </LineStyle>"
   "      <PolyStyle>"
   "        <color>880000ff</color>"
   "        <fill>0</fill>"
   "        <outline>1</outline>"
   "      </PolyStyle>"
   "    </Style>"
   "    <Polygon>"
   "      <outerBoundaryIs>"
   "        <LinearRing>"
   "          <coordinates>10,10 0,10 0,0 10,0 10,10</coordinates>"
   "        </LinearRing>"
   "      </outerBoundaryIs>"
   "      <innerBoundaryIs>"
   "        <LinearRing>"
   "          <coordinates>5,5 1,5 1,1 5,1 5,5</coordinates>"
   "        </LinearRing>"
   "      </innerBoundaryIs>"
   "      <innerBoundaryIs>"
   "        <LinearRing>"
   "          <coordinates>3,3 2,3 2,2 3,2 3,3</coordinates>"
   "        </LinearRing>"
   "      </innerBoundaryIs>"
   "      <innerBoundaryIs>"
   "        <LinearRing>"
   "          <coordinates>8,8 6,8 6,6 8,6 8,8</coordinates>"
   "        </LinearRing>"
   "      </innerBoundaryIs>"
   "    </Polygon>"
   "  </Placemark>"
   "</kml>");

std::string TEST_TIME_KML_DATA(
   "<kml>"
   "  <Document>"
   "    <Placemark>"
   "      <name>Always on</name>"
   "      <Point>"
   "        <coordinates>1,1</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <Placemark>"
   "      <name>Turns on After 2010</name>"
   "      <TimeStamp>"
   "        <when>2010</when>"
   "      </TimeStamp>"
   "      <Point>"
   "        <coordinates>2,1</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <Placemark>"
   "      <name>Turns on After 2011</name>"
   "      <TimeSpan>"
   "        <begin>2011</begin>"
   "      </TimeSpan>"
   "      <Point>"
   "        <coordinates>3,1</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <Placemark>"
   "      <name>Only on Before 2011</name>"
   "      <TimeSpan>"
   "        <end>2011</end>"
   "      </TimeSpan>"
   "      <Point>"
   "        <coordinates>4,1</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <Placemark>"
   "      <name>On Between 2011 and 2012</name>"
   "      <TimeSpan>"
   "        <begin>2011</begin>"
   "        <end>2012</end>"
   "      </TimeSpan>"
   "      <Point>"
   "        <coordinates>5,1</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "  </Document>"
   "</kml>");

std::string TEST_PHOTO_OVERLAY_KML_DATA(
   "<kml>"
   "  <PhotoOverlay>"
   "    <Icon>"
   "      <href>http://osm-kml.appspot.com/static/falconview_symposium.png</href>"
   "    </Icon>"
   "    <Point>"
   "      <coordinates>1,1</coordinates>"
   "    </Point>"
   "  </PhotoOverlay>"
   "</kml>"
   );

std::string TEST_STYLE_WORK_AROUND_KML_DATA(
   "<kml>"
   "  <Document>"
   "    <Style id=\"test_icon_style\">"
   "      <IconStyle>"
   "        <scale>3.0</scale>"
   "        <heading>90.0</heading>"
   "        <Icon>"
   "          <href>http://osm-kml.appspot.com/static/falconview_symposium.png</href>"
   "        </Icon>"
   "      </IconStyle>"
   "    </Style>"
   "    <Placemark>"
   "      <styleUrl>test_icon_style</styleUrl>"
   "      <Point>"
   "        <coordinates>1,1</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "  </Document>"
   "</kml>"
   );

std::string TEST_HIT_TEST_INVISIBLE_FOLDER_KML_DATA(
   "<kml>"
   "  <Folder>"
   "    <visibility>0</visibility>"
   "    <Placemark>"
   "      <Point>"
   "        <coordinates>1,1</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <Placemark>"
   "      <Point>"
   "        <coordinates>0,1,1</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "  </Folder>"
   "</kml>"
   );

std::string ONLY_TIMESTAMPS_KML_DATA(
   "<kml>"
   "  <Document>"
   "    <Placemark>"
   "      <name>2012</name>"
   "      <TimeStamp>"
   "        <when>2012</when>"
   "      </TimeStamp>"
   "      <Point>"
   "        <coordinates>1,1</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <Placemark>"
   "      <name>2013</name>"
   "      <TimeStamp>"
   "        <when>2013</when>"
   "      </TimeStamp>"
   "      <Point>"
   "        <coordinates>2,1</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <Placemark>"
   "      <name>2014</name>"
   "      <TimeStamp>"
   "        <when>2014</when>"
   "      </TimeStamp>"
   "      <Point>"
   "        <coordinates>3,1</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "  </Document>"
   "</kml>");

std::string TEST_SCREEN_OVERLAY_WIN_PATH_KML_DATA(
   "<kml>"
   "  <ScreenOverlay>"
   "    <Icon>"
   "      <href>D:\\exclude\\fv_dev_gov\\FalconView\\trunk\\Test\\KML Overlay\\osm-kml\\static\\falconview_symposium.png</href>"
   "    </Icon>"
   "  </ScreenOverlay>"
   "</kml>"
   );

std::string TEST_EXPLICIT_STYLE_URL_KML_DATA(
   "<kml>"
   "  <Folder>"
   "    <Placemark>"
   "      <styleUrl>http://osm-kml.appspot.com/static/only_styles.kml#yellow</styleUrl>"
   "      <Style>"
   "         <IconStyle>"
   "           <scale>3.0</scale>"
   "         </IconStyle>"
   "      </Style>"
   "      <Point>"
   "        <coordinates>0,1</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "    <Placemark>"
   "      <styleUrl>http://osm-kml.appspot.com/static/only_styles.kml#blue</styleUrl>"
   "      <Style>"
   "         <IconStyle>"
   "           <scale>2.0</scale>"
   "         </IconStyle>"
   "      </Style>"
   "      <Point>"
   "        <coordinates>1,1</coordinates>"
   "      </Point>"
   "    </Placemark>"
   "  </Folder>"
   "</kml>"
   );

std::string TEST_MODEL_KML_DATA(
   "<kml>"
   "  <Placemark>"
   "    <Model>"
   "      <Location>"
   "        <latitude>1.0</latitude>"
   "        <longitude>1.0</longitude>"
   "      </Location>"
   "    </Model>"
   "  </Placemark>"
   "</kml>"
   );
